DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id        SERIAL PRIMARY KEY,
    login     VARCHAR(50),
    password  VARCHAR(64),
    email     VARCHAR(50),
    is_deleted BOOLEAN DEFAULT FALSE
);
