ALTER TABLE users
ADD COLUMN new_id UUID;

ALTER TABLE users
DROP CONSTRAINT users_pkey;

ALTER TABLE users ADD PRIMARY KEY (new_id);

ALTER TABLE users
DROP COLUMN id;

ALTER TABLE users
RENAME COLUMN new_id TO id;

ALTER TABLE users
ALTER COLUMN password TYPE VARCHAR(161);